In [1]:
import time
import hashlib

import numpy as np
import pandas as pd

/Users/jiandewu/.pyenv/versions/3.9.6/envs/testvenv/lib/python3.9/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


In [9]:
data = pd.read_csv("data/data.csv")

In [22]:
def k_mers(data, n):
    return [[s[i:i + n].lower() for i in range(len(s) - n)] for s in data]

In [45]:
from collections import Counter

def build_vocab(data):
    word_counts = Counter(row.lower() for sample in data for row in sample)
    vocab = [w for w, f in iter(word_counts.items())]
    return vocab

In [46]:
kmer_array = k_mers(data['Seq'], 2)
vocab = build_vocab(kmer_array)

In [73]:
# row_count = np.array([[]])

# for row in kmer_array:
    
row_count = [[Counter(row)[key] for key in vocab] for row in kmer_array ]

In [75]:
import stats

row_count = np.array(row_count)
print(row_count)
z = stats.zscore(row_count, axis=1, ddof=1)
print(z)

[[ 47  48  27 ...  42  49   3]
 [586 630 528 ... 480 456 160]
 [720 804 704 ... 581 563 244]
 ...
 [ 45  51  54 ...  31  19  30]
 [133 138  93 ...  97  86  31]
 [ 79  89  87 ...  58  42  39]]


AttributeError: module 'stats' has no attribute 'zscore'