In [2]:
import time

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn import datasets
from sklearn import svm
from sklearn.metrics import f1_score
from sklearn import metrics

from libsvm.svmutil import *

In [21]:
data_x = np.load("data/linear_features/linear/k1p8nor3.npy")
data_y = np.load("data/linear_features/data_y.npy")

In [22]:
data_x[0]

array([[-2.19668248e+02,  9.40386981e+02, -1.62594804e+03,
         1.45552731e+03, -7.10638789e+02,  1.75014826e+02,
        -1.58410534e+01,  1.74442281e+00, -7.74587535e-03],
       [-1.81074111e+02,  7.69450225e+02, -1.32374822e+03,
         1.18195569e+03, -5.75330654e+02,  1.39529950e+02,
        -1.22435813e+01,  1.99919682e+00, -1.09691091e-02],
       [ 2.82237092e+02, -1.19101915e+03,  2.02826060e+03,
        -1.77893787e+03,  8.40374450e+02, -1.95729308e+02,
         1.61783896e+01, -1.94652899e+00,  1.00902858e+00],
       [ 9.16036127e+01, -4.11879641e+02,  7.51180387e+02,
        -7.23228424e+02,  3.92605037e+02, -1.11054788e+02,
         1.19320700e+01, -1.69162204e+00,  1.00893680e+00]])

In [23]:
data_x = data_x.reshape(data_x.shape[0],-1)
print(data_x.shape)

(2432, 36)


In [24]:
x_train, x_test, y_train, y_test = train_test_split(data_x, data_y, test_size=0.20, shuffle=True, random_state=12)

In [25]:
clf = svm.SVC(kernel='linear', C=1, class_weight='balanced').fit(x_train, y_train)
score = clf.score(x_test, y_test)
y_pred = clf.predict(x_test)
print("score:", score)
print("macro:", f1_score(y_test, y_pred, average='macro'))


In [6]:
import pickle
with open('data/linear_features/model/test_svm.pickle', 'wb') as f:
    pickle.dump(clf, f)

In [13]:
with open('data/linear_features/model/k2n3_1122.pickle', 'rb') as f:
    clf2 = pickle.load(f)
y_pred = clf2.predict(x_test)
print("macro:", f1_score(y_test, y_pred, average='macro'))

ValueError: X.shape[1] = 21 should be equal to 48, the number of features at training time

In [18]:
np.unique(y_train, return_counts=True)

(array([0, 1]), array([ 147, 1798]))

In [5]:
prob = svm_problem(y_train, x_train, isKernel=True)
param = svm_parameter('-t 0 -w0 1 -w1 10')
m = svm_train(prob, param)
p_label, p_acc, p_val = svm_predict(y_test, x_test, m)

print("macro:", f1_score(y_test, p_label, average='macro'))
print(metrics.confusion_matrix(y_test, p_label) / len(y_test))

Accuracy = 51.3347% (250/487) (classification)
macro: 0.40729614395094826
[[0.04517454 0.03696099]
 [0.44969199 0.46817248]]
